In [1]:
import torch

In [2]:
tensor_1 = torch.tensor(8)

print(tensor_1)
print(tensor_1.dtype)

tensor(8)
torch.int64


In [3]:
tensor_2 = torch.tensor([1.,2.,3.])

print(tensor_2)
print(tensor_2.dtype)

tensor([1., 2., 3.])
torch.float32


In [4]:
tensor_3 = torch.tensor([1,2,3,4])

print(tensor_3)
print(tensor_3.dtype)

tensor([1, 2, 3, 4])
torch.int64


In [5]:
tensor_4 = torch.tensor([[1.2,3],[4,6]])

print(tensor_4)
print(tensor_4.dtype)

tensor([[1.2000, 3.0000],
        [4.0000, 6.0000]])
torch.float32


In [6]:
tensor_4.shape

torch.Size([2, 2])

In [7]:
tensor_5 = torch.tensor([
    [[1,2,3],[4,5,6]],
    [[10,20,30],[40,50,60]]
])

print(tensor_5)
print(tensor_5.dtype)
print(tensor_5.shape)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[10, 20, 30],
         [40, 50, 60]]])
torch.int64
torch.Size([2, 2, 3])


In [9]:
shape = (2,3)

ones = torch.ones(shape)
print(ones)

zeros = torch.zeros(shape)
print(zeros)

random = torch.randn(shape)
print(random)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[ 1.0197, -0.1653, -0.1551],
        [-0.5881, -0.5358,  1.3258]])


In [10]:
tensor_1.device

device(type='cpu')

In [ ]:
x_data = torch.tensor([[1,2],[3,4]])

w = torch.tensor([4.,5.], requires_grad= True)

x_data.requires_grad, w.requires_grad

(False, True)

In [16]:
a = torch.tensor(5., requires_grad=True)
b = torch.tensor(4., requires_grad=True)
c = torch.tensor(1., requires_grad=True)

y = a + b
z = c * y

z

tensor(9., grad_fn=<MulBackward0>)

In [17]:
z.grad_fn, y.grad_fn, a.grad_fn

(<MulBackward0 at 0x2370f1bac20>, <AddBackward0 at 0x2370f1ba110>, None)

In [ ]:
a = torch.tensor([[1,2],[3,4]])
b = torch.tensor([[10,20], [30,40]])

a*b #element wise multiplication , same shape

tensor([[ 10,  40],
        [ 90, 160]])

In [ ]:
a@b #matrix multiplication , 2x2,2x3

tensor([[ 70, 100],
        [150, 220]])

In [28]:
ten = torch.tensor([[6.,2.,4.], [6.,8.,2]])

ten.mean()

tensor(4.6667)

In [30]:
ten.mean(dim=0)

tensor([6., 5., 3.])

In [29]:
ten.mean(dim=1)

tensor([4.0000, 5.3333])

In [33]:
x = torch.arange(12).reshape(3,4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [36]:
x[:,1]

tensor([1, 5, 9])

In [38]:
torch.argmax(ten, dim=1)

tensor([0, 1])